### ISSUE TITLE
Waziup Dashboard

### ISSUE THREAD

**Issue by j-forster** [Waziup/waziup-dashboard#1]
Hi @cdupont 

as I already mentioned somewhere else, I created a Waziup dashboard using a lot of functionality that the broker provides.

See https://github.com/j-forster/Waziup-Dashboard
(because GitHub is https only and Waziup isn't, you need to download the dashboard..)

For now, it's useful for graphical stuff like virtual fencing, which was one of my major goals for the project work.

 I would really like to know your views on this.

**Comment by cdupont** [comment]
Hi Johann,
that looks amazing!! I find the code is also really neat and clean. Great job.
If I understand, this is entirely based on HTML5/CSS/JS?
What were the major difficulty of this project? How does the technology compares to REACT (which we use)? How to integrate some of your work in the project?

**Comment by j-forster** [comment]
Hi Corentin,
with REACT, the dashboard loads (bundle.js)[http://dashboard.waziup.io/static/js/bundle.js] with 256,385 lines of JS code, then redirects the user to the keycloak login page ... redirects back and evaluates the 256,385 lines of JS code again.. 
However, who knows if REACT is the tool of choice in one or two years. Why not Backbone.js, or the Polymer Project?

I made myself a small module-loader library and split the dashboard into [13 modules](https://github.com/j-forster/Waziup-Dashboard/tree/master/www/view), which makes the login page amazingly fast and resource efficient. Also have a look at the broker interface ([broker.js](https://github.com/j-forster/Waziup-Dashboard/blob/master/www/js/broker.js)).

But I don't know how to integrate the new dashboard into the project.. You can host it next to the official dashboard if you want, but the new dashboard covers all of the features the existing dashboard has..

**Comment by cdupont** [comment]
I quite agree with your analysis. This make me think of this W3C rule: "the rule least power": https://www.w3.org/2001/tag/doc/leastPower-2006-02-23.html

**Comment by cdupont** [comment]
Johann could you give me your email?

**Comment by j-forster** [comment]
It's 📧 johannforster15(at)gmail.com.

**Comment by cdupont** [comment]
closing as this is old.
