### ISSUE TITLE
sensor list can't be fully displayed 

### ISSUE THREAD

**Issue by sabrine2020** [Waziup/waziup-dashboard#3]
Hello,
I can’t see the full list of sensors, I can't navigate to the end of the list.

**Comment by cdupont** [comment]
We might activate infinite scrolling instead of paginating: https://griddlegriddle.github.io/v0-docs/infiniteScroll.html

**Comment by malishahi** [comment]
Fixed the problem with UI, and sensor data. Please check the same address for tests.

**Comment by cdupont** [comment]
Look good, closing
