### ISSUE TITLE
Error when fetching sensors: 403 not_authorized

### ISSUE THREAD

**Issue by sabrine2020** [Waziup/waziup-dashboard#51]
Hello,
I got this error on the dashboard when I connected with waziup visitor user:

![image](https://user-images.githubusercontent.com/11886594/42311057-3e932020-803d-11e8-8175-6fba88fb568e.png)

**Comment by cdupont** [comment]
Hi Sabrine,
I connected with the waziup user, but I don't get the errors.
Could you clean the errors and see if other are coming? Maybe they are old.

**Comment by sabrine2020** [comment]
Hello, 
Tried again today and I still see the errors ..

Sabrine
